version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db01
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5400:5432"

  nats:
    image: nats-streaming:latest
    ports:
      - "4222:4222"

  nats-ui:
    image: piotrpersona/nats-streaming-ui:latest
    ports:
      - "8282:8282"
    environment:
      STAN_URL: "http://nats:4222"
      STAN_MONITOR_URL: "http://nats:8222"
      STAN_CLUSTER: test-cluster





volumes:
  postgres: